spring:
    profiles:
        active:
        - dog
        - EN
        - dev
ragnarzone:
    username: YmlUserName
    password: YmlPassword
    jdbcurl: YmlUrl

---
spring:
    profiles: prod
ragnarzone:
    username: YmlProdUserName
    password: YmlProdPassword
    jdbcurl: YmlProdUrl